#!/bin/bash

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
cur_brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if [ $# != 1 ]; then
    let bright_percent=$cur_brightness*100/$max_brightness
    if ((bright_percent < 100)); then
        let bright_percent=bright_percent+1
    fi
    echo $bright_percent
    exit 0
else
    bright_desired=$1
    if ((bright_desired > 100)); then
        echo "Invalid brightness percentage"
        exit 1
    elif ((bright_desired < 0)); then
        echo "Invalid brightness percentage"
        exit 1
    fi
    let bright_desired=$bright_desired*$max_brightness/100
    sudo bash -c "echo $bright_desired > /sys/class/backlight/intel_backlight/brightness"
fi
exit 0

